version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - ./uploads:/app/uploads
      - ./data:/app/data
      - ./runs:/app/runs
      - ./config:/app/config
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - DATABASE_URL=sqlite:///roses.db
    command: flask --app app.py run --host=0.0.0.0 --port=5000
    restart: unless-stopped 