# ``` This file must be used only for local development ```
version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000" 
    volumes:
      - .:/app
      - ./data:/app/data
      - ./uploads:/app/uploads
      - ./runs:/app/runs
      - ./config:/app/config
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
    command: ["gunicorn", "--bind", "0.0.0.0:5000", "--workers", "4", "--timeout", "300", "app:create_app()"]
    restart: unless-stopped 